### ISSUE TITLE
mypy error using effect.combine

### ISSUE THREAD

**Issue by ericgj** [suned/pfun#90]
Minimal example:

```python
from typing import TypeVar, Any
from pfun.effect import Try, combine, catch

A = TypeVar("A")

def test(*effects: Try[Exception,A]) -> Try[Exception,None]:
    return combine(*effects)(lambda *a: None)
```

Blows up with a mypy internal error:

![image](https://user-images.githubusercontent.com/291002/133149544-4bfbf690-8d16-4c3c-9202-66f21730929d.png)

It doesn't matter if I move that lambda to a function.

(Probably a mypy issue, as I tried with the latest dev version of mypy (0.920dev) and didn't get the error. But note I had to disable the pfun mypy_plugin on the dev version, got a different error.)

**Comment by suned** [comment]
Thanks for the report!

I think this error is legitimate, since type inference in general doesn't work that great for lambdas, so probably the argument types or return types can't be extracted in the way the plugin expects. I don't think that case is handled. Expect a patch soon :)

**Comment by suned** [comment]
Thanks for the report! The issue seems to be the use of starags which isn't handled correctly in the plugin. I think this needs to be special cased unfortunately, so it might take a moment before I can produce a fix

**Comment by ericgj** [comment]
No worries, I didn't end up needing combine for what I was doing. I did wonder if a non-starargs version of combine, lift, etc would work better.

**Comment by suned** [comment]
Good to hear.

>  I did wonder if a non-starargs version of combine, lift, etc would work better.

it would be easier to type, but you would have to write overloaded definitions for some number of arguments, so it would also be less flexible.
